name: BiocCheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  BiocCheck:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Bioconductor and BiocCheck
        run: |
          install.packages('BiocManager')
          BiocManager::install(version = 'release')
          BiocManager::install('BiocCheck')
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: packages/cfomics
          extra-packages: any::rcmdcheck

      - name: Run BiocCheck
        run: |
          BiocCheck::BiocCheck(
            'packages/cfomics',
            `new-package` = TRUE,
            `no-check-vignettes` = TRUE,
            `no-check-bioc-help` = TRUE
          )
        shell: Rscript {0}
